### ISSUE TITLE
如何添加自定义关键词呢？

### ISSUE THREAD

**Issue by dzcdhj** [houbb/segment#1]
自定义关键词加在哪里？比如人名，然后分词的时候作为一个整体。
自定义词典怎么加载？

**Comment by houbb** [comment]
maven 项目直接放在 resources 目录，创建一个文件 `segment_define_dict.txt`，内容格式如下：

```
张三
李四
```

每一行代表一个人名，使用 `utf-8` 编码。
这样会自定义词典会被自动加载。
