### ISSUE TITLE
使用完后能释放内存吗

### ISSUE THREAD

**Issue by SkyD666** [houbb/segment#10]
使用完分词功能后能够释放掉占用的内存吗

**Comment by houbb** [comment]
字典占用的内存是不能的，出于性能和内存的平衡。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SkyD666 ***@***.***&gt;
发送时间: 2023年3月21日 23:41
收件人: houbb/segment ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/segment] 使用完后能释放内存吗 (Issue #10)





 
使用完分词功能后能够释放掉占用的内存吗

**Comment by SkyD666** [comment]
对于仅使用一次分词的场景，给用户一个手动释放内存的功能或许比较好

**Comment by houbb** [comment]
什么场景会只用一次分词呢？


可以说下，看下常见的话加一下这个特性



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SkyD666 ***@***.***&gt;
发送时间: 2023年3月22日 14:22
收件人: houbb/segment ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [houbb/segment] 使用完后能释放内存吗 (Issue #10)





 
对于仅使用一次分词的场景，给用户一个手动释放内存的功能或许比较好

**Comment by SkyD666** [comment]
例如分词是一个软件里的一部分功能，用户用过一次后就不再用分词了，而一直在用软件的功能，但是分词这部分一直占用资源。这点主要在Android上有要求（尽量少占用内存，无服务器的APP）

**Comment by houbb** [comment]
作为软件客户端是存在这个问题，还以为作为服务器。


我后续加一下这个特性。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SkyD666 ***@***.***&gt;
发送时间: 2023年3月22日 15:00
收件人: houbb/segment ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [houbb/segment] 使用完后能释放内存吗 (Issue #10)





 
例如分词是一个软件里的一部分功能，用户用过一次后就不再用分词了，而一直在用软件的功能，但是分词这部分一直占用资源。这点主要在Android上有要求（尽量少占用内存，无服务器的APP）

**Comment by SkyD666** [comment]
感谢

**Comment by houbb** [comment]
V0.2.0 已支持词特性，使用愉快~

参见：[主动释放资源](https://github.com/houbb/segment#%E4%B8%BB%E5%8A%A8%E9%87%8A%E6%94%BE%E8%B5%84%E6%BA%90)
