### ISSUE TITLE
香蕉苹果

### ISSUE THREAD

**Issue by robbietree8** [houbb/segment#5]
香蕉苹果的分词结果还是["香蕉苹果"]，这个是为啥

ps: 苹果香蕉的分词结果是["苹果", "香蕉"]

**Comment by houbb** [comment]
【香蕉苹果】在默认的词组中被收录了（结巴的词库），所以会被当做一个词。

比如【望梅止渴】是一个成语，但是【止渴望梅】不一定是。

**Comment by robbietree8** [comment]
可以通过自定义词典的方式覆盖这个行为吗

**Comment by houbb** [comment]
可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: robbietree8 ***@***.***&gt;
发送时间: 2021年12月21日 11:20
收件人: houbb/segment ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [houbb/segment] 香蕉苹果 (Issue #5)





 
可以通过自定义词典的方式覆盖这个行为吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
