### ISSUE TITLE
自定义词库可以更改分隔符吗

### ISSUE THREAD

**Issue by Fraudsterrrr** [houbb/segment#7]
因为有些专有名词会带有空格，希望能整个切出，如何更改自定义词库的分隔符。

**Comment by Bbblithe** [comment]
请问一下大哥，这个自定义词库怎么项目中使用，但readme没看懂，只写了添加文件如何配置

**Comment by Fraudsterrrr** [comment]
只是初步看了下 还没接入项目 不清楚咋弄
