### ISSUE TITLE
支持词频统计么？

### ISSUE THREAD

**Issue by fendo8888** [houbb/segment#9]
支持词频统计么？

**Comment by houbb** [comment]
没做，关键词之类的是独立的项目，也不难。
项目的定位是分词。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fendo8888 ***@***.***&gt;
发送时间: 2022年11月24日 11:22
收件人: houbb/segment ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/segment] 支持词频统计么？ (Issue #9)





 
支持词频统计么？

**Comment by houbb** [comment]
V0.3.0 加了工具方法，便于使用。

参见：[词频统计](https://github.com/houbb/segment#%E7%BB%9F%E8%AE%A1%E5%88%86%E8%AF%8D%E5%87%BA%E7%8E%B0%E7%9A%84%E6%AC%A1%E6%95%B0)
